export interface DataType {
    "id": number,
    "Session": number,
    "Statut de l’établissement de la filière de formation (public, privé…)": string,
    "Code UAI de l'établissement": string,
    "Établissement": string,
    "Code départemental de l’établissement": number,
    "Département de l’établissement": string,
    "Région de l’établissement": string,
    "Académie de l’établissement": string,
    "Filière de formation très agrégée": string,
    "Filière de formation": string,
    "Concours communs et banques d'épreuves": string,
    "Filière de formation détaillée": string,
    "Filière de formation très détaillée": string,
    "Lien de la formation sur la plateforme Parcoursup": string,
    "Coordonnées GPS de la formation": string,
    "Capacité de l’établissement par formation": number,
    "Effectif total des candidats pour une formation": number,
    "Dont effectif des candidates pour une formation": number,
    "Effectif total des candidats en phase principale": number,
    "Dont effectif des candidats ayant postulé en internat": number,
    "Effectif des candidats néo bacheliers généraux en phase principale": number,
    "Dont effectif des candidats boursiers néo bacheliers généraux en phase principale": number,
    "Effectif des candidats néo bacheliers technologiques en phase principale": number,
    "Dont effectif des candidats boursiers néo bacheliers technologiques en phase principale": number,
    "Effectif des candidats néo bacheliers professionnels en phase principale": number,
    "Dont effectif des candidats boursiers néo bacheliers professionnels en phase principale": number,
    "Effectif des autres candidats en phase principale": number,
    "Effectif total des candidats en phase complémentaire": number,
    "Effectif des candidats néo bacheliers généraux en phase complémentaire": number,
    "Effectif des candidats néo bacheliers technologique en phase complémentaire": number,
    "Effectif des candidats néo bacheliers professionnels en phase complémentaire": number,
    "Effectifs des autres candidats en phase complémentaire": number,
    "Effectif total des candidats classés par l’établissement en phase principale": number,
    "Effectif des candidats classés par l’établissement en phase complémentaire": number,
    "Effectif des candidats classés par l’établissement en internat (CPGE)": number,
    "Effectif des candidats classés par l’établissement hors internat (CPGE)": number,
    "Effectif des candidats néo bacheliers généraux classés par l’établissement": number,
    "Dont effectif des candidats boursiers néo bacheliers généraux classés par l’établissement": number,
    "Effectif des candidats néo bacheliers technologiques classés par l’établissement": number,
    "Dont effectif des candidats boursiers néo bacheliers technologiques classés par l’établissement": number,
    "Effectif des candidats néo bacheliers professionnels classés par l’établissement": number,
    "Dont effectif des candidats boursiers néo bacheliers professionnels classés par l’établissement": number,
    "Effectif des autres candidats classés par l’établissement": number,
    "Effectif total des candidats ayant reçu une proposition d’admission de la part de l’établissement": number,
    "Rang du dernier appelé": number,
    "Effectif total des candidats ayant accepté la proposition de l’établissement (admis)": number,
    "Dont effectif des candidates admises": number,
    "Effectif des admis en phase principale": number,
    "Effectif des admis en phase complémentaire": number,
    "Dont effectif des admis ayant reçu leur proposition d’admission à l'ouverture de la procédure principale": number,
    "Dont effectif des admis ayant reçu leur proposition d’admission avant le baccalauréat": number,
    "Dont effectif des admis ayant reçu leur proposition d’admission avant la fin de la procédure principale": number,
    "Dont effectif des admis en internat": number,
    "Dont effectif des admis boursiers néo bacheliers": number,
    "Effectif des admis néo bacheliers": number,
    "Effectif des admis néo bacheliers généraux": number,
    "Effectif des admis néo bacheliers technologiques": number,
    "Effectif des admis néo bacheliers professionnels": number,
    "Effectif des autres candidats admis": number,
    "Dont effectif des admis néo bacheliers sans information sur la mention au bac": number,
    "Dont effectif des admis néo bacheliers sans mention au bac": number,
    "Dont effectif des admis néo bacheliers avec mention Assez Bien au bac": number,
    "Dont effectif des admis néo bacheliers avec mention Bien au bac": number,
    "Dont effectif des admis néo bacheliers avec mention Très Bien au bac": number,
    "Effectif des admis néo bacheliers généraux ayant eu une mention au bac": number,
    "Effectif des admis néo bacheliers technologiques ayant eu une mention au bac": number,
    "Effectif des admis néo bacheliers professionnels ayant eu une mention au bac": number,
    "Dont effectif des admis issus du même établissement (BTS/CPGE)": number,
    "Dont effectif des admises issues du même établissement (BTS/CPGE)": number,
    "Dont effectif des admis issus de la même académie": number,
    "Dont effectif des admis issus de la même académie (Paris/Créteil/Versailles réunies)": number,
    "% d’admis ayant reçu leur proposition d’admission à l'ouverture de la procédure principale": number,
    "% d’admis ayant reçu leur proposition d’admission avant le baccalauréat": number,
    "% d’admis ayant reçu leur proposition d’admission avant la fin de la procédure principale": number,
    "% d’admis dont filles": number,
    "% d’admis néo bacheliers issus de la même académie": number,
    "% d’admis néo bacheliers issus de la même académie (Paris/Créteil/Versailles réunies)": number,
    "% d’admis néo bacheliers issus du même établissement (BTS/CPGE)": number,
    "% d’admis néo bacheliers boursiers": number,
    "% d’admis néo bacheliers": number,
    "% d’admis néo bacheliers sans information sur la mention au bac": number,
    "% d’admis néo bacheliers sans mention au bac": number,
    "% d’admis néo bacheliers avec mention Assez Bien au bac": number,
    "% d’admis néo bacheliers avec mention Bien au bac": number,
    "% d’admis néo bacheliers avec mention Très Bien au bac": number,
    "% d’admis néo bacheliers généraux": number,
    "Dont % d’admis avec mention": number,
    "% d’admis néo bacheliers technologiques": number,
    "Dont % d’admis avec mention__1": number,
    "% d’admis néo bacheliers professionnels": number,
    "Dont % d’admis avec mention__2": number,
    "tri": string,
}